{% set version = "2.5.4" %}

package:
  name: tig
  version: {{ version }}

source:
  url: https://github.com/jonas/tig/releases/download/tig-{{ version }}/tig-{{ version }}.tar.gz
  sha256: c48284d30287a6365f8a4750eb0b122e78689a1aef8ce1d2961b6843ac246aa7
