{% set version = "3.1.6" %}

package:
  name: q
  version: {{ version }}

source:
  url: https://github.com/harelba/q/archive/refs/tags/v{{ version }}.tar.gz

requirements:
  build:
    - python {{ python }}
    - setuptools
    - six

  run:
    - python
    - six

about:
  home: http://harelba.github.io/q/
