#!/usr/bin/env perl

# @author Masahiro Kasahara (masahiro@kasahara.ws)

use strict;

use Bio::SeqIO;
use Bio::DB::GenBank;
use Getopt::Long;

my $inputfile    = '';
my $inputformat  = 'fasta';
my $outputfile   = '';
my $outputformat = 'fasta';
my $neededhelp   = 0;
my @idstrings    = ();

my $genbank_query = 0;
my $genbank_id    = 0;
my $genbank_acc   = 0;
my $genbank_gi    = 0;

GetOptions('help'             => \$neededhelp,
	   'inputfilename=s'  => \$inputfile,
	   'inputformat=s'    => \$inputformat,
	   'outputfilename=s' => \$outputfile,
	   'outputformat=s'   => \$outputformat,
	   'query=s'          => \@idstrings,
	   'massive'          => \$genbank_query,
	   'id'               => \$genbank_id,
	   'accession'        => \$genbank_acc,
	   'gi'               => \$genbank_gi 
	   );

if($inputfile eq '') {
    $inputfile = shift;
    $inputfile = '' unless(defined $inputfile);
}

sub usage
{
    print STDERR "To convert sequence file\n";
    print STDERR "   usage: convertsequence.pl --inputfilename <inputfilename> [--inputformat <inputformat>]";
    print STDERR " [--outputfilename <outputfilename>] [--outputformat <outputformat>]\n";
    print STDERR "To get a sequence(s) from genbank\n";
    print STDERR "   usage: convertsequence [--id|--accession|--gi|--massive] --query <query string1> [--query <query string2> ...]";
    print STDERR " [--outputfilename <outputfilename>] [--outputformat <outputformat>]\n";
}

my $num_genbank_modes = $genbank_id + $genbank_acc + $genbank_gi + $genbank_query;

if($neededhelp) {
    usage();
    exit 0;
}
if(@idstrings > 0 && $inputfile ne '') {
    print STDERR "ERROR: --query cannot be combined with an input file.\n";
    usage();
    exit 1;
}
if(@idstrings == 0 && $inputfile eq '') {
    usage();
    exit 1;
}
if($num_genbank_modes > 1) {
    print STDERR "ERROR: only one of --id, --accession, --gi and --massive may be given.\n";
    usage();
    exit 1;
}
if($num_genbank_modes > 0 && @idstrings == 0) {
    print STDERR "ERROR: --id, --accession, --gi and --massive require at least one --query.\n";
    usage();
    exit 1;
}

my $inseq;

if(@idstrings) {
    my $genbank = Bio::DB::GenBank->new();
    if($genbank_query) {
	# --massive: treat the query strings as an Entrez query rather than as
	# a list of identifiers, so that a single query may return many
	# sequences.
	require Bio::DB::Query::GenBank;
	my $query_string = join(' OR ', @idstrings);
	my $query = Bio::DB::Query::GenBank->new('-db'    => 'nucleotide',
						 '-query' => $query_string);
	$inseq = $genbank->get_Stream_by_query($query);
    } elsif($genbank_acc) {
	$inseq = $genbank->get_Stream_by_acc([@idstrings]);
    } elsif($genbank_gi) {
	$inseq = $genbank->get_Stream_by_gi([@idstrings]);
    } else {
	# --id, and the default when no lookup type was given.
	$inseq = $genbank->get_Stream_by_id([@idstrings]);
    }
} else {
    $inseq   = Bio::SeqIO->new('-file'   => "<$inputfile",
				  '-format' => $inputformat );
}

my $seq_out;
if($outputfile eq '') {
    $seq_out = Bio::SeqIO->new('-fh'     => \*STDOUT,
                               '-format' => $outputformat);
} else {
    $seq_out = Bio::SeqIO->new('-file'   => ">$outputfile",
                               '-format' => $outputformat);
}

my $numprocessedsequences = 0;

while (my $seq = $inseq->next_seq) {
    $seq_out->write_seq($seq);
    $numprocessedsequences++;
}

print STDERR "$numprocessedsequences processed\n";

=pod

=head1 NAME

convertsequence - Convert sequence file into another format

=head1 SYNOPSYS

To convert a sequence into a file of another format,

B<convertsequence> --inputfile E<lt>input fileE<gt> --inputformat E<lt>format of input fileE<gt> --outputfile E<lt>output fileE<gt> --outputformat E<lt>format of output fileE<gt>

To get a sequence(s) from genbank,

B<convertsequence> [--id|--accession|--gi|--massive] --query E<lt>query string1E<gt> [--query E<lt>query string2E<gt> ...] [--outputfilename E<lt>outputfilenameE<gt>] [--outputformat E<lt>outputformatE<gt>]

=head1 DESCRIPTION

This utility is to convert a sequence file into a file of another format,
or to get a sequence(s) from GenBank remotely.

=head1 OPTIONS

=over 8

=item B<--inputfilename> E<lt>fileE<gt>

The sequence file to read. If it is not given, the first non-option argument is
used instead. Mutually exclusive with B<--query>.

=item B<--inputformat> E<lt>formatE<gt>

The format of the input file, as understood by L<Bio::SeqIO>. The default is
C<fasta>.

=item B<--outputfilename> E<lt>fileE<gt>

The file to write. If it is not given, the sequences are written to the
standard output.

=item B<--outputformat> E<lt>formatE<gt>

The format of the output, as understood by L<Bio::SeqIO>. The default is
C<fasta>.

=item B<--query> E<lt>stringE<gt>

A query to send to GenBank. The option may be repeated to give several queries
at once. Mutually exclusive with an input file.

=item B<--id>

Interpret every B<--query> as a sequence identifier (this is also what happens
when none of B<--id>, B<--accession>, B<--gi> and B<--massive> is given).

=item B<--accession>

Interpret every B<--query> as an accession number.

=item B<--gi>

Interpret every B<--query> as a GI number.

=item B<--massive>

Interpret the B<--query> strings as an Entrez query (several queries are joined
with C<OR>) instead of as identifiers, so that a single query may retrieve many
sequences at once. The query is issued against the C<nucleotide> database.

=item B<--help>

Show a short usage message and exit.

=back

At most one of B<--id>, B<--accession>, B<--gi> and B<--massive> may be given,
and all of them require at least one B<--query>.

=head1 EXAMPLES

Inputs 'hoge.gb' in GenBank format and convert it into 'hoge.fasta' in FASTA format.

	B<convertsequence> --inputfile hoge.gb --inputformat genbank --outputfile hoge.fasta --outputformat fasta

Get a sequence by accession numbers from remote GenBank.
You can give multiple queries by simply repeating --query option as many as you want.

        B<convertsequence> --accession --query AB090307 --query AB090308 --outputfile hoge.fasta --outputformat fasta

If you need to know vailable formats, see BioPerl documentation for details.
Even author doesn't know well about it.

=cut
