#!/bin/bash

# tmux requires unrecognized OSC sequences to be wrapped with DCS tmux;
# <sequence> ST, and for all ESCs in <sequence> to be replaced with ESC ESC. It
# only accepts ESC backslash for ST. We use TERM instead of TMUX because TERM
# gets passed through ssh.
function print_osc() {
    if [[ $TERM == screen* ]]; then
        printf "\033Ptmux;\033\033]"
    else
        printf "\033]"
    fi
}

# More of the tmux workaround described above.
function print_st() {
    if [[ $TERM == screen* ]]; then
        printf "\a\033\\"
    else
        printf "\a"
    fi
}

function load_version() {
    if [ -z ${IMGCAT_BASE64_VERSION+x} ]; then
        IMGCAT_BASE64_VERSION=$(base64 --version 2>&1)
        export IMGCAT_BASE64_VERSION
    fi
}

function b64_encode() {
    load_version
    if [[ $IMGCAT_BASE64_VERSION =~ GNU ]]; then
        # Disable line wrap
        base64 -w0
    else
        base64
    fi
}

function b64_decode() {
    load_version
    if [[ $IMGCAT_BASE64_VERSION =~ fourmilab ]]; then
        BASE64ARG=-d
    elif [[ $IMGCAT_BASE64_VERSION =~ GNU ]]; then
        BASE64ARG=-di
    else
        BASE64ARG=-D
    fi
    base64 $BASE64ARG
}

# print_image filename inline base64contents print_filename
#   filename: Filename to convey to client
#   inline: 0 or 1
#   base64contents: Base64-encoded contents
#   print_filename: If non-empty, print the filename
#                   before outputting the image
#   width: Width in terms of the terminal width. See https://iterm2.com/3.2/documentation-images.html for how to specify width.
#   height: Height in terms of the terminal height. See https://iterm2.com/3.2/documentation-images.html for how to specify height.
function print_image() {
    print_osc
    printf '1337;File='
    if [[ -n $1 ]]; then
        printf "name=%s;" "$(printf "%s" "$1" | b64_encode)"
    fi

    printf "%s" "$3" | b64_decode | wc -c | awk '{printf "size=%d",$1}'
    printf ";inline=%s" "$2"
    if [[ -n $5 ]]; then
	    echo -n ";width="; echo -n "$5"
    fi
    if [[ -n $6 ]]; then
	    echo -n ";height="; echo -n "$6"
    fi
    printf ":"
    printf "%s" "$3"
    print_st
    printf '\n'
    if [[ -n $4 ]]; then
        echo "$1"
    fi
}

function error() {
    echo "ERROR: $*" 1>&2
}

function show_help() {
    echo "Usage: imgcat2 [-p] [-W width] [-H height] filename ..." 1>&2
    echo "   or: cat filename | imgcat2" 1>&2
    echo "   or: imgcat2 -u url" 1>&2
    echo "" 1>&2
    echo "Options:" 1>&2
    echo "  -p, --print          print the filename before the image" 1>&2
    echo "  -W, --width  VALUE   image width  (e.g. 100px, 50%, 10; default 35%)" 1>&2
    echo "  -H, --height VALUE   image height (e.g. 100px, 50%, 10)" 1>&2
    echo "  -u, --url    URL     download an image from URL and show it" 1>&2
    echo "  -h, --help           show this help" 1>&2
    echo "" 1>&2
    echo "VALUE for -W/-H follows the iTerm2 spec:" 1>&2
    echo "  N    number of character cells" 1>&2
    echo "  Npx  number of pixels" 1>&2
    echo "  N%   percentage of the terminal width/height" 1>&2
}

function check_dependency() {
    if ! (builtin command -V "$1" >/dev/null 2>&1); then
        echo "imgcat: missing dependency: can't find $1" 1>&2
        exit 1
    fi
}

## Main

if [ -t 0 ]; then
    has_stdin=f
else
    has_stdin=t
fi

# Show help if no arguments and no stdin.
if [ $has_stdin = f ] && [ $# -eq 0 ]; then
    show_help
    exit
fi

check_dependency awk
check_dependency base64
check_dependency wc

print_width="35%"
print_height=""
# Look for command line flags.
while [ $# -gt 0 ]; do
    case "$1" in
    -h | --help)
        show_help
        exit
        ;;
    -W | --width)
	print_width=$2
	shift
	;;
    -H | --height)
	print_height=$2
	shift
	;;
    -p | --p | --print)
        print_filename=1
        ;;
    -u | --u | --url)
        check_dependency curl
        encoded_image=$(curl -s "$2" | b64_encode) || (
            error "No such file or url $2"
            exit 2
        )
        has_stdin=f
        print_image "$2" 1 "$encoded_image" "$print_filename" "$print_width" "$print_height"
        set -- "${@:1:1}" "-u" "${@:3}"
        if [ "$#" -eq 2 ]; then
            exit
        fi
        ;;
    -*)
        error "Unknown option flag: $1"
        show_help
        exit 1
        ;;
    *)
        if [ -r "$1" ]; then
            has_stdin=f
            print_image "$1" 1 "$(b64_encode <"$1")" "$print_filename" "$print_width" "$print_height"
        else
            error "imgcat: $1: No such file or directory"
            exit 2
        fi
        ;;
    esac
    shift
done

# Read and print stdin
if [ $has_stdin = t ]; then
    print_image "" 1 "$(cat | b64_encode)" ""
fi

exit 0
