#!/usr/bin/env python

import argparse
from simpleodspy.sodsspreadsheet import SodsSpreadSheet
from simpleodspy.sodsxlsx import SodsXlsx
from simpleodspy.sodsods import SodsOds

def main():
    parser = argparse.ArgumentParser(description="Converts .ods file to .xlsx")
    parser.add_argument('input', help="Input file (.ods)")
    parser.add_argument('output', help="Output file (.xlsx)")
    parser.add_argument('--debug', help="Enable debugging")
    args = parser.parse_args()
    if args.debug:
        print "Input: " + args.input
        print "Output: " + args.output
    spread_sheet = SodsSpreadSheet()
    odsdoc = SodsOds(spread_sheet)
    odsdoc.load(args.input)
    xlsxdoc = SodsXlsx(spread_sheet)
    xlsxdoc.save(args.output)

if __name__ == "__main__":
    main()

